name: Build and deploy ASP.Net Core app to Azure Web App - OrderApi2025

on:
  push:
    branches:
      - main
    paths:
      - 'OrderWebApi/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Order API
        run: dotnet build OrderWebApi/OrderWebApi.csproj --configuration Release

      - name: Publish Order API
        run: dotnet publish OrderWebApi/OrderWebApi.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: orderapi-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: orderapi-app
          path: ./publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OrderApi2025'
          slot-name: 'Production'
          package: ./publish
