name: Build and Deploy OrderApi2025 to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'OrderWebApi/**'  # only trigger if OrderWebApi folder changes
  workflow_dispatch:      # allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # or your target version

      - name: Restore dependencies
        run: dotnet restore ./OrderWebApi/OrderWebApi.csproj

      - name: Build
        run: dotnet build ./OrderWebApi/OrderWebApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./OrderWebApi/OrderWebApi.csproj --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: orderapi-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: orderapi-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}
          enable-AzPSSession: false
          environment: azurecloud

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'OrderApi2025'   # your Azure App Service name
          slot-name: 'Production'
          package: ./publish
